cygwin: Fix strptime warning
After 8.1.2326, cygwin warns this:

```
evalfunc.c: In function 'f_strptime':
evalfunc.c:7452:9: warning: implicit declaration of function 'strptime'; did you mean 'strftime'? [-Wimplicit-function-declaration]
      || strptime((char *)str, (char *)fmt, &tmval) == NULL
         ^~~~~~~~
         strftime
evalfunc.c:7452:52: warning: comparison between pointer and integer
      || strptime((char *)str, (char *)fmt, &tmval) == NULL
                                                    ^~
```

This is caused that some headers are included before defining
_XOPEN_SOURCE, then define _XOPEN_SOURCE and include time.h, but it is
too late for strptime().

This patch seems to fix the problem. (But not sure if this is the best
fix.)