src/vim9compile.c: Fixing 'key' issues in compile_dict()
We run our coverity scans during CentOS Stream 9 development and
coverity reported several issues on Vim. Then the issues are divided by
importance (USE_AFTER_FREEs, RESOURCE_LEAKs, BUFFER_OVERFLOWs etc. have
a priority) and the important ones are reviewed further.

I reviewed Vim's important issues - they were false positives in most
cases, but I found the following issue as real:

 Error: USE_AFTER_FREE (CWE-416):
 vim82/src/vim9compile.c:3304: freed_arg: "generate_PUSHS" frees "key".
 vim82/src/vim9compile.c:3311: deref_arg: Calling "dict_find"
 dereferences freed pointer "key".
 # 3309|       if (key != NULL)
 # 3310|       {
 # 3311|->         item = dict_find(d, key, -1);
 # 3312|           if (item != NULL)
 # 3313|           {

'key' is freed in 'generate_PUSHS()' if 'cctx->ctx_skip' is 'SKIP_YES',
but the pointer is not set to NULL afterwards, so it can be accessed
further down.
Also, if 'generate_PUSHS()' returns FAIL, 'key' is not freed.

The PR fixes both issues.

I will attach the coverity scans results too - the important ones with
my notes and all results.